#!/bin/bash

#warna untuk output
GREEEN='\033[0;32m'
NC='\033[0m' # No Color

echo "Script Di Mulai Pada $(date)"

clear_logs() {

local files=("$@")

for log in "${files[@]}"; do

if [ -f "$log" ]; then

echo "$log clear"

echo > "$log"

fi

done

}

log_files=($(find /var/log/ -name "*.log"))

clear_logs "${log_files[@]}"

err_files=($(find /var/log/ -name "*.err"))

clear_logs "${err_files[@]}"

mail_files=($(find /var/log/ -name "*.mail"))

clear_logs "${mail_files[@]}"

specific_logs=(

"/var/log/syslog"

"/var/log/btmp"

"/var/log/messages"

"/var/log/debug"

)

clear_logs "${specific_logs[@]}"

echo -e "\n${GREEN}Clear Log Berhasil${NC}\n"

if [ ! -f /var/log/xray/access.log ]; then

echo  "File /var/log/xray/access.log    tidak ditemukan!"

exit1

fi

xray_status=$(systemctl is-active xray.service)

if [ $"xray_status" != "active" ]; then

echo "$(date): Layanan xray sedang down. Merestart service xray..." >> /var/log/xray/monitor.log

sudo systemctl restart xray.service

if [ $? eq- 0 ]; then

echo "Service Xray Berhasil di Restart."

echo "$(date): Service Xray Berhasil direstart." >> /var/log/xray/monitor.log

else

echo "Gagal merestart service Xray."

echo "$(date): Service Xray Gagal direstart." >> /var/log/xray/monitor.log

fi

else

echo "Layanan Xray Akctif."

fi

